kafka:
  bootstrap-servers: localhost:9092
  topic:
    name: customer-orders-avro4
    consumer-group: neworders-cg2

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productDetails
    username: root
    password: root
  jpa:
   hibernate:
     use-new-id-generator-mappings: false
     ddl-auto: create
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect